# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Monte Carlo estimated covariance, CUDA accelerated
#'
#' @param x a vector of distances
#' @param s a vector of random samples from the estimated spectral density
#' @return a vector or some shit I dunno
mc <- function(x, s) {
    .Call(`_gpumc_mc`, x, s)
}

